# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setEnabled(True)
        self.send_button.setGeometry(QtCore.QRect(880, 580, 51, 41))
        self.send_button.setObjectName("send_button")
        self.message = QtWidgets.QLineEdit(self.centralwidget)
        self.message.setGeometry(QtCore.QRect(270, 580, 601, 41))
        self.message.setObjectName("message")
        self.chat = QtWidgets.QTextEdit(self.centralwidget)
        self.chat.setGeometry(QtCore.QRect(270, 10, 661, 561))
        self.chat.setReadOnly(True)
        self.chat.setObjectName("chat")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 261, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.chat_list_tab = QtWidgets.QWidget()
        self.chat_list_tab.setObjectName("chat_list_tab")
        self.chat_list = QtWidgets.QListWidget(self.chat_list_tab)
        self.chat_list.setGeometry(QtCore.QRect(0, 40, 251, 531))
        self.chat_list.setAutoFillBackground(True)
        self.chat_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chat_list.setMovement(QtWidgets.QListView.Static)
        self.chat_list.setViewMode(QtWidgets.QListView.ListMode)
        self.chat_list.setObjectName("chat_list")
        item = QtWidgets.QListWidgetItem()
        self.chat_list.addItem(item)
        self.add_chat_button = QtWidgets.QPushButton(self.chat_list_tab)
        self.add_chat_button.setGeometry(QtCore.QRect(203, 0, 41, 30))
        self.add_chat_button.setObjectName("add_chat_button")
        self.add_chat_name = QtWidgets.QLineEdit(self.chat_list_tab)
        self.add_chat_name.setGeometry(QtCore.QRect(0, 0, 121, 30))
        self.add_chat_name.setObjectName("add_chat_name")
        self.add_chat_key = QtWidgets.QLineEdit(self.chat_list_tab)
        self.add_chat_key.setGeometry(QtCore.QRect(120, 0, 81, 30))
        self.add_chat_key.setObjectName("add_chat_key")
        self.tabWidget.addTab(self.chat_list_tab, "")
        self.connection_data = QtWidgets.QWidget()
        self.connection_data.setAutoFillBackground(False)
        self.connection_data.setObjectName("connection_data")
        self.nickname = QtWidgets.QLineEdit(self.connection_data)
        self.nickname.setGeometry(QtCore.QRect(10, 20, 111, 30))
        self.nickname.setObjectName("nickname")
        self.password = QtWidgets.QLineEdit(self.connection_data)
        self.password.setGeometry(QtCore.QRect(120, 20, 121, 30))
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setObjectName("password")
        self.ip = QtWidgets.QLineEdit(self.connection_data)
        self.ip.setGeometry(QtCore.QRect(10, 50, 111, 30))
        self.ip.setObjectName("ip")
        self.port = QtWidgets.QSpinBox(self.connection_data)
        self.port.setGeometry(QtCore.QRect(120, 50, 121, 30))
        self.port.setToolTipDuration(-1)
        self.port.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.port.setMinimum(1)
        self.port.setMaximum(65535)
        self.port.setProperty("value", 2026)
        self.port.setObjectName("port")
        self.connect_button = QtWidgets.QPushButton(self.connection_data)
        self.connect_button.setGeometry(QtCore.QRect(10, 80, 231, 30))
        self.connect_button.setObjectName("connect_button")
        self.tabWidget.addTab(self.connection_data, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.message.setPlaceholderText(_translate("MainWindow", "Message"))
        self.chat.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        __sortingEnabled = self.chat_list.isSortingEnabled()
        self.chat_list.setSortingEnabled(False)
        item = self.chat_list.item(0)
        item.setText(_translate("MainWindow", "#main"))
        self.chat_list.setSortingEnabled(__sortingEnabled)
        self.add_chat_button.setText(_translate("MainWindow", "Add"))
        self.add_chat_name.setPlaceholderText(_translate("MainWindow", "Chat name"))
        self.add_chat_key.setPlaceholderText(_translate("MainWindow", "Chat key"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chat_list_tab), _translate("MainWindow", "Messages"))
        self.nickname.setWhatsThis(_translate("MainWindow", "Login"))
        self.nickname.setText(_translate("MainWindow", "Name"))
        self.password.setWhatsThis(_translate("MainWindow", "Password"))
        self.password.setText(_translate("MainWindow", "Password"))
        self.ip.setWhatsThis(_translate("MainWindow", "IP"))
        self.ip.setText(_translate("MainWindow", "127.0.0.1"))
        self.port.setWhatsThis(_translate("MainWindow", "Port"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.connection_data), _translate("MainWindow", "Connection data"))
